name: pocket_provisioner
description: A mobile utility for VoIP handset provisioning.
version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Architecture & Data
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2 
  
  # Networking
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  network_info_plus: ^5.0.1
  
  # Hardware & Permissions
  mobile_scanner: ^5.0.0
  permission_handler: ^11.0.1
  wakelock_plus: ^1.1.0
  path_provider: ^2.1.1

  # UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
